<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>DeskLofi</AssemblyName>
    <RootNamespace>DeskLofi</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <None Update="Data\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Music\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
